// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScanJob(arg1) {
  return window['go']['main']['App']['CancelScanJob'](arg1);
}

export function ExportDiagnostics() {
  return window['go']['main']['App']['ExportDiagnostics']();
}

export function GetAboutInfo() {
  return window['go']['main']['App']['GetAboutInfo']();
}

export function GetAppStatus() {
  return window['go']['main']['App']['GetAppStatus']();
}

export function GetDatabaseStatus() {
  return window['go']['main']['App']['GetDatabaseStatus']();
}

export function GetCommonScanPaths() {
  return window['go']['main']['App']['GetCommonScanPaths']();
}

export function GetDownloadsPath() {
  return window['go']['main']['App']['GetDownloadsPath']();
}

export function GetLoginItemStatus() {
  return window['go']['main']['App']['GetLoginItemStatus']();
}

export function GetRuntimeSetupStatus() {
  return window['go']['main']['App']['GetRuntimeSetupStatus']();
}

export function GetScanJob(arg1) {
  return window['go']['main']['App']['GetScanJob'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListAppLogEntries(arg1) {
  return window['go']['main']['App']['ListAppLogEntries'](arg1);
}

export function ListQuarantineRecords() {
  return window['go']['main']['App']['ListQuarantineRecords']();
}

export function ListScanJobs() {
  return window['go']['main']['App']['ListScanJobs']();
}

export function LoadScanResults(arg1) {
  return window['go']['main']['App']['LoadScanResults'](arg1);
}

export function MoveQuarantineRecordToTrash(arg1) {
  return window['go']['main']['App']['MoveQuarantineRecordToTrash'](arg1);
}

export function MoveScanResultToTrash(arg1) {
  return window['go']['main']['App']['MoveScanResultToTrash'](arg1);
}

export function OpenFullDiskAccessSettings() {
  return window['go']['main']['App']['OpenFullDiskAccessSettings']();
}

export function OpenNotificationSettings() {
  return window['go']['main']['App']['OpenNotificationSettings']();
}

export function OpenQuarantineLocation(arg1) {
  return window['go']['main']['App']['OpenQuarantineLocation'](arg1);
}

export function OpenScanResultLocation(arg1) {
  return window['go']['main']['App']['OpenScanResultLocation'](arg1);
}

export function PermanentlyDeleteQuarantineRecord(arg1) {
  return window['go']['main']['App']['PermanentlyDeleteQuarantineRecord'](arg1);
}

export function PermanentlyDeleteScanResult(arg1) {
  return window['go']['main']['App']['PermanentlyDeleteScanResult'](arg1);
}

export function QuarantineScanResult(arg1) {
  return window['go']['main']['App']['QuarantineScanResult'](arg1);
}

export function ReadClamdLog(arg1) {
  return window['go']['main']['App']['ReadClamdLog'](arg1);
}

export function ReadFreshclamLog(arg1) {
  return window['go']['main']['App']['ReadFreshclamLog'](arg1);
}

export function RemoveUserData(arg1) {
  return window['go']['main']['App']['RemoveUserData'](arg1);
}

export function RestoreQuarantineRecord(arg1) {
  return window['go']['main']['App']['RestoreQuarantineRecord'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectScanFiles() {
  return window['go']['main']['App']['SelectScanFiles']();
}

export function SelectScanFolder() {
  return window['go']['main']['App']['SelectScanFolder']();
}

export function StartScan(arg1, arg2) {
  return window['go']['main']['App']['StartScan'](arg1, arg2);
}

export function UpdateDatabase() {
  return window['go']['main']['App']['UpdateDatabase']();
}
