// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelScanJob(arg1:string):Promise<boolean>;

export function ExportDiagnostics():Promise<string>;

export function GetAboutInfo():Promise<main.AboutInfo>;

export function GetAppStatus():Promise<main.AppStatus>;

export function GetDatabaseStatus():Promise<main.DatabaseStatus>;

export function GetCommonScanPaths():Promise<Array<{label:string;path:string}>>;

export function GetDownloadsPath():Promise<string>;

export function GetLoginItemStatus():Promise<main.LoginItemStatus>;

export function GetRuntimeSetupStatus():Promise<main.RuntimeSetupStatus>;

export function GetScanJob(arg1:string):Promise<main.ScanJob>;

export function GetSettings():Promise<main.Settings>;

export function GetSystemPermissionStatus():Promise<main.SystemPermissionStatus>;

export function ListAppLogEntries(arg1:number):Promise<Array<main.LogEntry>>;

export function ListQuarantineRecords():Promise<Array<main.QuarantineRecord>>;

export function ListScanJobs():Promise<Array<main.ScanJob>>;

export function LoadScanResults(arg1:string):Promise<Array<main.ScanResult>>;

export function LoadScanResultsPage(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<main.ScanResultsPage>;

export function MarkScanResultStatus(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MoveQuarantineRecordToTrash(arg1:string):Promise<main.QuarantineRecord>;

export function MoveScanResultToTrash(arg1:main.ScanResult):Promise<void>;

export function OpenFullDiskAccessSettings():Promise<void>;

export function OpenNotificationSettings():Promise<void>;

export function OpenQuarantineLocation(arg1:main.QuarantineRecord):Promise<void>;

export function OpenScanResultLocation(arg1:main.ScanResult):Promise<void>;

export function PermanentlyDeleteQuarantineRecord(arg1:string):Promise<main.QuarantineRecord>;

export function PermanentlyDeleteScanResult(arg1:main.ScanResult):Promise<void>;

export function QuarantineScanResult(arg1:main.ScanResult):Promise<main.QuarantineRecord>;

export function ReadClamdLog(arg1:number):Promise<Array<string>>;

export function ReadFreshclamLog(arg1:number):Promise<Array<string>>;

export function RemoveUserData(arg1:main.UserDataRemovalOptions):Promise<main.UserDataRemovalResult>;

export function RestoreQuarantineRecord(arg1:string):Promise<main.QuarantineRecord>;

export function SaveSettings(arg1:main.Settings):Promise<main.Settings>;

export function SelectScanFiles():Promise<Array<string>>;

export function SelectScanFolder():Promise<string>;

export function StartScan(arg1:Array<string>,arg2:main.ScanOptions):Promise<main.ScanJob>;

export function UpdateDatabase():Promise<main.DatabaseStatus>;
